apiVersion: apps/v1
kind: Deployment
metadata:
  name: tokenization-service
spec:
  selector:
    matchLabels:
      app: tokenization-service
  replicas: 1
  template:
    metadata:
      labels:
        app: tokenization-service
    spec:
      automountServiceAccountToken: false
      containers:
        - name: tokenization-service
          image: mferpena/tokenization-service:v1.0.0
          ports:
            - containerPort: 3000
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: tokenization-secrets
                  key: jwt-secret
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: ""
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: tokenization-service
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
  selector:
    app: tokenization-service
